name: Integration

on:
  push:
    branches: [main, master, latest]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/job-lint.yml

  typecheck:
    uses: ./.github/workflows/job-typecheck.yml

  test:
    uses: ./.github/workflows/job-test.yml
