name: Integration

on:
  push:
    branches: [main, master, latest]
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/job-lint.yml

  typecheck:
    uses: ./.github/workflows/job-typecheck.yml

  test:
    uses: ./.github/workflows/job-test.yml
