name: Reusable typecheck

on:
  workflow_call: {}

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dev dependencies
        run: pip install -e ".[dev]" --pre

      - name: Mypy
        run: mypy src
